In [10]:
import pandas as pd

df= pd.read_csv("https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/delaney_solubility_with_descriptors.csv")
df

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion   logS
0     2.59540  167.850                0.0            0.000000 -2.180
1     2.37650  133.405                0.0            0.000000 -2.000
2     2.59380  167.850                1.0            0.000000 -1.740
3     2.02890  133.405                1.0            0.000000 -1.480
4     2.91890  187.375                1.0            0.000000 -3.040
...       ...      ...                ...                 ...    ...
1139  1.98820  287.343                8.0            0.000000  1.144
1140  3.42130  286.114                2.0            0.333333 -4.925
1141  3.60960  308.333                4.0            0.695652 -3.893
1142  2.56214  354.815                3.0            0.521739 -3.790
1143  2.02164  179.219                1.0            0.461538 -2.581

[1144 rows x 5 columns]

In [3]:
y = df['logS']
y

0      -2.180
1      -2.000
2      -1.740
3      -1.480
4      -3.040
        ...
1139    1.144
1140   -4.925
1141   -3.893
1142   -3.790
1143   -2.581
Name: logS, Length: 1144, dtype: float64

In [4]:
x = df.drop ('logS', axis=1)
x

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion
0     2.59540  167.850                0.0            0.000000
1     2.37650  133.405                0.0            0.000000
2     2.59380  167.850                1.0            0.000000
3     2.02890  133.405                1.0            0.000000
4     2.91890  187.375                1.0            0.000000
...       ...      ...                ...                 ...
1139  1.98820  287.343                8.0            0.000000
1140  3.42130  286.114                2.0            0.333333
1141  3.60960  308.333                4.0            0.695652
1142  2.56214  354.815                3.0            0.521739
1143  2.02164  179.219                1.0            0.461538

[1144 rows x 4 columns]

In [5]:
x.describe()

           MolLogP        MolWt  NumRotatableBonds  AromaticProportion
count  1144.000000  1144.000000        1144.000000         1144.000000
mean      2.449133   204.631675           2.173951            0.364932
std       1.866003   102.620500           2.627398            0.343305
min      -7.571400    16.043000           0.000000            0.000000
25%       1.414900   122.126000           0.000000            0.000000
50%       2.340300   183.594500           1.000000            0.375000
75%       3.406475   270.715750           3.000000            0.666667
max      10.388600   780.949000          23.000000            1.000000

In [8]:
x.head()

   MolLogP    MolWt  NumRotatableBonds  AromaticProportion
0   2.5954  167.850                0.0                 0.0
1   2.3765  133.405                0.0                 0.0
2   2.5938  167.850                1.0                 0.0
3   2.0289  133.405                1.0                 0.0
4   2.9189  187.375                1.0                 0.0

In [20]:
from sklearn.tree import Standard
df=DecisionTreeRegressor(random_state=0)
df.fit(x,y)

ImportError: cannot import name 'Standard' from 'sklearn.tree' (C:\Users\vinod\anaconda3\Lib\site-packages\sklearn\tree\__init__.py)

In [21]:
import pandas as pd

melbourne_file_path = '../input/melbourne-housing-snapshot/melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path) 
melbourne_data.columns

FileNotFoundError: [Errno 2] No such file or directory: '../input/melbourne-housing-snapshot/melb_data.csv'